[target.aarch64-unknown-linux-musl]
pre-build = [
  "apt-get update && apt-get -y install libfontconfig1-dev"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
  "apt-get update && apt-get -y install libfontconfig1-dev"
]
